### ISSUE TITLE
pault.ag is down

### ISSUE THREAD

**Issue by FranciscoMSM** [paultag/go-debian#102]
Hey! It looks pault.ag is down. This is breaking `dep ensure` for us. Thanks.

**Comment by paultag** [comment]
@FranciscoMSM done -- between this and https://github.com/paultag/go-debian/issues/101 I'm going to migrate off that VPS ASAP to S3. Sorry about that. My fault 100%.

**Comment by FranciscoMSM** [comment]
@paultag thanks for dealing with this situations so quickly. Appreciate it.

**Comment by paultag** [comment]
I moved `pault.ag` over to S3 + CloudFront + ACM - please let me know if you see any disruption, but I believe the root cause of this is finally sorted.
