### ISSUE TITLE
Consider providing an io.SectionReader interface to ar content

### ISSUE THREAD

**Issue by charles-dyfis-net** [paultag/go-debian#114]
At present, archive members can only be read in order: continuing to the next one consumes all data from the existing LimitedReader.

This makes it somewhat more difficult than it would otherwise be to check debsig-style signatures (for which an `io.MultiReader(controlReader, dataReader)` would otherwise be the perfect thing to pass to `openpgp.CheckDetachedSignature`) without (necessarily and unambiguously) copying everything into RAM.

At the expense of requiring a seekable file handle on the underlying file, one could switch from a LimitedReader interface to a SectionReader, to make reads still possible after `ar.Next()` has been called.

See blakesmith/ar#11 for a concrete idea of what's being proposed. (I'd be happy to provide a concrete implementation here as well should it be welcome; implemented above on top of `blakesmith/ar` before discovering that go-debian existed).

**Comment by paultag** [comment]
Makes total sense, thank you @charles-dyfis-net! I'd welcome such a changeset, and moving to an external ar library would be A-OK. There wasn't one at the time when this was written or I would have used one :)

**Comment by paultag** [comment]
Done via #115
