### ISSUE TITLE
some formats are not supported

### ISSUE THREAD

**Issue by cincly** [paultag/go-debian#121]
example: http://mirrors.aliyun.com/ubuntu/pool/main/l/linux-aws/linux-image-unsigned-5.15.0-1004-aws_5.15.0-1004.6_amd64.deb

file list:

```bash
$ tar -xvf linux-image-unsigned-5.15.0-1004-aws_5.15.0-1004.6_amd64.deb 
x debian-binary
x control.tar
x data.tar
```

**Comment by errordeveloper** [comment]
Looks like this check fails `.tar` files, it only detects `.tar.*` files:

https://github.com/paultag/go-debian/blob/9df3f2696ca17d00f363102749a06c3ed2f69ea3/deb/tarfile.go#L102-L105

Will open a PR shortly.
