### ISSUE TITLE
Can't handle comments in "debian/control"

### ISSUE THREAD

**Issue by tianon** [paultag/go-debian#14]
Thanks to #13, I've tracked down the source of why I can't parse `debian/control` of `src:golang`:
```
Line "# DO NOT EDIT THIS FILE. EDIT debian/control.* instead!\n" is not 'key: val'
```

**Comment by tianon** [comment]
I think a fix could be to implement a pass-through reader that strips comment lines completely; then it could just wrap the `Reader` itself in the couple functions where `#` comments are OK and leave the parsing code intact otherwise.  Thoughts?

As an aside, can comments be at EOL too? (ie, `Depends: some, packages, here # lolwut comment`)

**Comment by paultag** [comment]
Having a reader strip them sounds the most clean, I guess, although there's something to be said for doing it properly. Hurm.

**Comment by tianon** [comment]
Thinking about this more, the question for me on which way to go kind of boils down to whether or not parsing/stripping "comment lines" in _all_ cases of RFC822 would actually be harmful.  I can't think of any cases where that might be, but I'm not as well-versed in the "RFC822 ecosystem" as you are, @paultag. :smile:

**Comment by paultag** [comment]
It means we drop them when we write it back out, but that's not the worst. Let's always strip for now.
