### ISSUE TITLE
add support for SHA512 control.DSC

### ISSUE THREAD

**Issue by strothj** [paultag/go-debian#54]
Can support for SHA512 be added?

The Docker repository's Release files contain SHA512 hashes.
https://apt.dockerproject.org/repo/dists/ubuntu-xenial/Release

**Comment by paultag** [comment]
@strothj absolutely! I'm doing the same in other `go-debian` code; that was likely me just hacking stuff together. I'll push something up soon if there's not a PR that beats me to it :)

:+1:
