### ISSUE TITLE
Arch.Is returns true when comparing arch:all with arch:any

### ISSUE THREAD

**Issue by stapelberg** [paultag/go-debian#63]
…this is because it treats any as a wildcard, matching anything (even arch:all).

Correct me if I’m wrong, but I think arch:all should not be matched by any. After all, that’s the critical distinction between the two, right?

Do you want me to send a PR to fix this or do you want to fix it yourself? :)

**Comment by paultag** [comment]
Yes please! We should also add more tests to cover this :)
