### ISSUE TITLE
Problem unmarshaling filehash fields from Release file

### ISSUE THREAD

**Issue by jeffw-wherethebitsroam** [paultag/go-debian#83]
I'm trying to use control to unmarshal a Release file, e.g.:

```
type Release struct {
	Origin        string
	Suite         string
	Codename      string
	Architectures []string
	Components    []string
	MD5Sum        []control.MD5FileHash
	SHA1          []control.SHA1FileHash
	SHA256        []control.SHA256FileHash
}

r := &Release{}
err := control.Unmarshal(r, reader)
```

But I get a panic:
panic: runtime error: index out of range
at:
pault.ag/go/debian/control/filehash.go:133

Which is in:
func (c *FileHash) unmarshalControl(algorithm, data string) error 

Firstly, is this the right way to use those FileHash fields? 

Secondly, things seem a bit odd with ```if len(data) < 4```:
1) Do you mean to check the length of ```vals```?
2) Why 4? I would have thought the length should be 3? 
```cb136f28a8c971d4299cc68e8fdad93a8ca7daf3 1131 dput-ng_1.9.dsc```

Jeff

**Comment by jeffw-wherethebitsroam** [comment]
Ok, from some of the test code I saw that I needed ```delim``` and ```strip```:

```
type Release struct {
	Origin        string
	Suite         string
	Codename      string
	Architectures []string
	Components    []string
	MD5Sum        []control.MD5FileHash    `control:"MD5Sum" delim:"\n" strip:"\n\r\t "`
	SHA1          []control.SHA1FileHash   `control:"SHA1" delim:"\n" strip:"\n\r\t "`
	SHA256        []control.SHA256FileHash `control:"SHA256" delim:"\n" strip:"\n\r\t "`
}
```
So parsing now works, but the check should maybe be ```if len(vals) < 3``` ?

Jeff

**Comment by stapelberg** [comment]
Thanks for your report. I can reproduce this issue.
